### PR TITLE
Added .gitignore. Created docs/session_2/03_working_with_jupyter_notebooks.ipynb

### PR DESCRIPTION
**Pull request by jcrattz**
Trello card: https://trello.com/c/QVBuX3Jk

Some content was borrowed from the [beginner's guide notebooks intro](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Beginners_guide/01_Jupyter_notebooks.ipynb). Should we link to that notebook in this one ("for more information, see this notebook")?

### CODE REVIEW

**Comment by jcrattz** [comment]
Actually, all of these particular commands work whether a cell is selected in command mode or edit mode (Ctrl, Alt, Shift + Enter shortcuts for running cells). Should we still mention command mode and edit mode?

**Comment by caitlinadams** [comment]
Ah, sorry, I should have been clearer; I was more referring to the commands such as `A` for new cell above, `B` for new cell below, etc. Those only work in command mode. 

I wonder if including those (and the explanation of command and edit mode) might be too complex? I think if you want to keep the parts about the other keyboard shortcuts (for working with cells rather than just running them), then you might need to add some information about edit and command modes. If you're happy to take them out, then there's no need to explain edit and command mode. As you say, all the short-cuts for running cells work independently of which mode you're in, so maybe it's best to keep these. 

As an alternative, you could mention that there are many keyboard shortcuts that help users navigate notebooks and that they can learn about them from https://towardsdatascience.com/jypyter-notebook-shortcuts-bf0101a98330.

**Comment by eefaye** [comment]
Hi @jcrattz , just thought I'd put my two cents in. Keen to get this merged!

I think this section does have slight overlap with `Running a notebook` that Oguz made for Session 1, but I really like the step by step on making a new notebook and running cells. It works really well as a quick recap from the previous session - you could even put that in the heading.
**How to run cells** --> **Recap: How to run cells** 

I would also suggest removing the alternative `Ctrl+Enter` and `Alt+Enter` explanations because they are covered by the shortcuts link at the bottom, and make the body of the text more daunting. It would be simpler if we kept it to two options - press the **Run** button, or press `Shift+Enter`.

If you wanted, you could link the **Help documentation** section under the **More information** heading. This section includes a rundown of the Beginner's Guide, so if people need more support they can go there.

`If you would like to review more Jupyter Notebook tutorials, have a look at the available [help documentation](../session_01/05_help_documentation.ipynb)`

**Comment by jcrattz** [comment]
@eefaye I've incorporated your suggestions.

**Pull request merged**
