### PR TITLE
Overhaul to unify session 1 material

### PR DESCRIPTION
**Pull request by caitlinadams**
I've done some work to simplify the session 1 material and change the structure to be more like training material than documentation. I've moved the Sandbox help documentation to the "other information section" to avoid overloading the user for the first week.

### CODE REVIEW

**Comment by andrewdhicks** [comment]
Looks good. I've updated it with the new videos that Tessa has uploaded.

**Comment by andrewdhicks** [comment]
@eefaye Slack is invite-only, so users need to go to slack.opendatacube.org to sign up, then they can access opendatacube.slack.com

So you'll probably want:
`[Open Data Cube Slack](http://slack.opendatacube.org/) and join the #de-africa-training channel`

**Comment by eefaye** [comment]
Added suggestions as above and in Slack. Not sure why `session_2/03_working_with_jupyter_notebooks.ipynb` is now a conflicted file with the master branch, but I haven't changed anything (of note) in it.

**Review by oyetkin — APPROVED** [review]
I think the Session 1 notebooks and the changes made by @caitlinadams look really good.  Here are some of my comments on the title video:

Audio has some background hiss and compression artifact (around 1:26).

SDGs should be spelled out as "Sustainable Development Goals" unless the users are expected to be extremely familiar with this terminology (2:42)

Background Noise (moving chairs) around 4:19

Email addresses hard to read 5:16
(blue on black background)

**Comment by eefaye** [comment]
Am currently incorporating Andrew C's comments from Trello.

**Pull request merged**
