### PR TITLE
Week 2 overhaul

### PR DESCRIPTION
**Pull request by eefaye**
Starting the PR so a draft website can be generated.

### CODE REVIEW

**Comment by eefaye** [comment]
Halfway through the data availability/metadata explorer revamp and on track to pull together loading/plotting material (as most of it already exists). Aiming to finish COB tomorrow AEST.

**Comment by AMA-AC** [comment]
I see that the "Edit on GitHub" text is rendered in a different font (vs pull 21) -- it looks like "font-family: FontAwesome" (pull 21 has it as "Arial, sans-serif").  Probably fine, but could be an indication that there's some CSS leaking somewhere that it shouldn't (or an un-closed element?)

**Comment by eefaye** [comment]
@caitlinadams  @andrewdhicks  The Session 2 content has come together nicely. Requesting review and consolidation.

**Review by caitlinadams — CHANGES_REQUESTED** [review]
Hi @eefaye and @jcrattz -- this is looking fantastic! I have a few minor comments around things that I think could be touched up, but otherwise I think this has come together really well, and offers a really good introduction to working with Digital Earth Africa data.

**Main page**
- Maybe change "We can then load specific datasets to produce colour imagery" to something that more clearly articulates what the user will do during the session: e.g. "This session will cover how to use the Digitial Africa Sandbox to load datasets for a given area of interest and make a colour image."

**Digitial Earth Africa Products**
- Add the video from Ken to this page, tie in with appropriate text to encourage the user to watch the video, then read the information. The video and text contain similar information this time around, so it may be appropriate to suggest that the user should watch the video to get an overview, then read the text below for more detail.
- For the definition of derived products, maybe change it to "datasets created by applying algorithms to satellite products." -- unless this terminology has been adopted from an existing source (like the roadmap)

**Digital Earth Africa Map**
- For the video text, mention that the video shows how to load a derived product (WOfS) and that users should follow the written instructions to learn how to load and visualise Landsat 8 data.

**Data availability**
- Looks great! 

**Loading data in the Sandbox**
- Under "Load packages and functions" it's probably worth reiterating that cells can be run by pressing `Shift + Enter` on the keyboard.
- In the "Load Landsat 8 data" section, the code jumps straight to arbitrary values for the x and y. Maybe it's worth adding some text before the screen shot saying that this exercise will load Landsat data for an area of Tanzania, defined using a pair of latitude coordinates (-6.90, -6.70) and a pair of longitude coordinates (39.20,  39.37). Explain that this makes a rectangle, and that data will be loaded for the rectangle. You could even add an extra step that gets them to run the `display_map` function with the given coordinates, so that they can directly see the bounding box. Up to you however, and all of this might be too much? Mostly, my point is that we should try and provide a bit more context about the specific area they're going to load, so they can have it in mind when typing out the code, rather than typing with no understanding. 
- Change to `EPSG:6933` as discussed this morning, and resolution to (-30, 30)
- For the "Troubleshooting code" section, is it worth adding a screenshot of some incorrect code and what the error message looks like? Might help in reassuring people if they see an error message and don't know how to interpret it. One example should be enough, but this can be left out if it takes up too much room or is too hard to clearly explain.
- After changing to `EPSG:6933` take care to check if the dataset dimensions change from "lat, lon" to "x, y" -- make sure you update the screenshots if they have changed.
- Make sure you update the data load for Sentinel-2, and explain that they'll also need to change the resolution from (-30, 30) to (-10, 10) to get the best Sentinel-2 resolution.
- In the "Conclusion", maybe add a sentence like "You've finished the second session of training" to let them know that they shouldn't expect any additional material for this session. Maybe add a recap of everything they've learnt, which includes how to visualise data in Maps, and explore available data in the Explorer. 

Amazing work! Thank you so much for pulling all of this together.

**Comment by eefaye** [comment]
All of @caitlinadams 's feedback has now been actioned. Will leave it to you, Caitlin, or @andrewdhicks to merge with `latest`, unless more changes are required.

**Review by caitlinadams — APPROVED** [review]
This is looking really good -- I have no further suggested changes.

@oyetkin -- could you please review in the next 24 hours so that we can complete any final changes and get this merged.

**Review by oyetkin — APPROVED** [review]
I think everything looks good overall. 

The video is useful.

Here are some comments:

Satellite products:
It may be useful (but not essential) to add the wavelengths to Spectral resolution for both LANDSAT8 and Sentinel2 as I had to look them up.

Digital Earth Africa Map:

Paragraph 2: The image (maps_datacatalogue_l8_boxed.PNG) is too small -- it may be a bit easier if rendered at a larger size

The "Load Data Exercise" Notebook is very good.

**Review by oyetkin — APPROVED** [review]
The changes look good to me

**Pull request merged**
