### PR TITLE
Session 5 content

### PR DESCRIPTION
**Pull request by eefaye**
Starting draft PR to check the build.

### CODE REVIEW

**Comment by eefaye** [comment]
@jcrattz  I am a little lost on what else we should include in 5-03, happy to discuss at tomorrow's meeting. 

Also I believe there has been some confusion but all webpage code is inline (code-formatted in markdown) as per Week 4 content, as opposed to code cells. 

The actual code has been put into the _static folder as the first draft of the solutions notebook.

**Comment by jcrattz** [comment]
I pushed the first version of the 5-03 notebook (analysis extension - [explanation of more complicated vegetation change detection notebook](https://trello.com/c/OVCfq7bm/60-week-5-3-overview-of-existing-change-detection-notebook-and-explanation-of-more-complicated-steps-not-covered-in-exercise)).

**Review by caitlinadams — APPROVED** [review]
Hi @eefaye and @jcrattz -- this looks fantastic. I think the introduction and exercise are really clear and well explained.

Andrew and I had a look at the final section and were concerned that it might still be too overwhelming for most of the users. As such, we've stripped it back to be an optional exercise to look through the existing case study notebook, with a suggestion that they bring any questions they have to the live session. That way, the people who are motivated will take a look (and might be less likely to be completely overwhelmed) and the people who are having more trouble with the material won't feel pressured to understand a complete case study. 

I've also changed the colour bar on the plot to match the actual case study -- this is because we've tended to plot loss of vegetation in red. I've updated the code, figure and interpretation, so should all be ok. 

@jcrattz -- Would you mind giving this a once over and letting me know what you think of the changes?

**Comment by jcrattz** [comment]
Thanks @caitlinadams.

Changes I made:
5-2: 
1. In the **Select area of interest** section, I changed "as well as seasonal changes for crops" to "or crops, where seasonal changes in vegetation greenness occur".
1. In the **Interpreting the plot** section, I renamed "pre-2016" to "2013-2015" and "post-2016" to "2016-2018".

Suggestions:
5-2: 
1. In the **Detect changes** section, though using the same string literals is a little clearer, it may be better to select the time ranges with the `time` variable (`time[0]`, `time[1]`) instead of the same string literals used in `time`.

**Comment by caitlinadams** [comment]
Thanks for your changes and suggestions, @jcrattz -- I've implemented the suggestion and added a sentence to explain why we use the `time` variable. Thanks for all your work!

**Pull request merged**
