### PR TITLE
Session 4-1 Band indices

### PR DESCRIPTION
**Pull request by eefaye**
`01_band_indices` is available for review. The only draft text in there is about expanding on applications of band indices in the second-last paragraph -- up for discussion.

### CODE REVIEW

**Comment by jcrattz** [comment]
In the section **Example: Normalised Difference Vegetation Index (NDVI)**, I think it would be nice to mention what kinds of terrain some ranges of NDVI may represent in scenes. [This is an article from USGS for Landsat](https://www.usgs.gov/land-resources/eros/phenology/science/ndvi-foundation-remote-sensing-phenology?qt-science_center_objects=0#qt-science_center_objects).

In the section **Band indices in research**:
1. We might want to clarify if the table of band indices are for Landsat 7, Landsat 8, Sentinel-2A/B, or some combination of those. Though they can be applied to data from at least Landsat 7 and 8, the results will be different since these satellites have different band ranges for the same band names, whereas Sentinel-2A and 2B have the same band ranges between each other. Mentioning that different ranges of values of band indices correspond to different types of terrain is important to do before the statement "It is important to remember band indices are not infallible, and can incorrectly label areas", since we haven't mentioned that ranges of the band indices map to different types of terrain (labels).
1. The term "spectral profiles" may need to be explained.
1. The phrase "refining combinations of bands" may need to be elaborated to clarify the meaning that different transformations of different band combinations differentiate different terrain types in varying degrees of accuracy, and research is done to determine the best bands and transformations (often normalized differences, or more generally, ratios of linear transformations of bands) for different applications. I'm not sure how much of that detail is appropriate - I'd love to hear your thoughts on it.
1. Consider changing "nuanced data analysis" to "nuanced and accurate data analysis".
1. For vegetation indices, we can note that NDVI is a good baseline vegetation proxy. But EVI is often more accurate, though it requires more data (3 bands vs 2 for NDVI). SAVI may perform better in arid regions (important in much of Africa - northern Ghana comes to mind, especially north east IIRC).
1. For urbanization indices, we can note that DBSI (`(SWIR1 - GREEN) / (SWIR1 + GREEN) - NDVI`) may perform better than NDBI in arid regions, but requires 4 bands (`swir1, green, nir, red`) instead of 2 for NDBI (`swir1, nir`) - so double the amount of data.

I think these proposals will increase understanding and engagement (vegetation and urbanization should be relevant). Let me know what you all think.

**Comment by eefaye** [comment]
@jcrattz Really helpful and well-thought out comments, thank you! 

1. A note added to mention different satellite products will produce different index values. I am assuming it is common to compare datasets with themselves (i.e. we generally do not compare Landsat8-NDVI with Sentinel2-NDVI) but if this is untrue we can remove it.

2. Phrase removed

3. Rewritten. It's proving difficult to reach a middle ground between summarising and being vague. @caitlinadams feel free to put your spin on it too.

4. Done

5, 6. I have incorporated some of this information in -- I think it's really interesting. Again, level and depth seem a bit subject and worth review.

**Review by caitlinadams — CHANGES_REQUESTED** [review]
Hi @eefaye -- this is looking great! Thanks for your work. I have a few minor suggestions:

- Could you add a link below the video that will allow users to download the slides?
- The table isn't quite displaying correctly (the band names are running into the wavelength ranges). It looks like the HTML you've used to put in a break hasn't come across. Could you restructure the table to put these in their own columns? Happy with any solution you can come up with for this.
Screen Shot 2020-09-14 at 11 02 21 am

**Comment by eefaye** [comment]
I am semi-confident I fixed the table formatting as I think I had some extra backslashes in the line breaks. Unfortunately, read the docs is broken again so I can't see it for myself at the moment -- if it's not fixed I'll put them in different columns.

**Pull request merged**
