### PR TITLE
Python basics extra session

### PR DESCRIPTION
**Pull request by eefaye**
Opening the PR for review purposes.

### CODE REVIEW

**Comment by eefaye** [comment]
Hi @nanaboamah89, I would appreciate your review when you have time!

My main concerns are:
 - Will this be useful to Python beginners?
 - Are the difficult concepts explained in an understandable way?
 - Is there anything else we should add?

Please feel free to push to the branch if you would like to make changes or add content. I have tried to make it non-specific to the DE Africa platform by avoiding ODC terms. Users can learn more about the ODC content by following the original training course.

Note 1: the `download` files in the `_static` folder are mirrors of the webpage files, so I wouldn't bother updating those until the content is finalised.
Note 2: ignore the Docs Check failure. It is pinging the ? symbols in the exercises when the webpage is being generated. I can't think of  a good replacement symbol and it does not affect the readability of the webpage or usability of the corresponding tutorial document.

**Comment by eefaye** [comment]
@caitlinadams , Edward and I have reviewed the contents of the python snippets. Keen to hear what you think. As usual, feel free to push changes to this branch. 

As before, the Docs Check failure is caused by the ? symbols in the exercises when the webpage is being generated. I can't think of a good replacement symbol and it does not affect the readability of the webpage or usability of the corresponding tutorial document, so I'm in good mind to leave it there. The errors are annoying though. Do you have any opinions on this matter?

**Review by NMoghaddam — APPROVED** [review]
The notebooks in python_basics were reviewed and all are in good shape. Made a few changes to the texts for instructions. The changes pushed to the python_basics branch.

**Comment by eefaye** [comment]
@andrewdhicks there has been a comment that the orange subheadings are occasionally difficult to read. I assume we are following a DEAfrica colour scheme here?

**Comment by andrewdhicks** [comment]
@eefaye only just say this notification. We are using the DEAfrica colours, so we could switch to green or blue pretty easily. Any preference?

**Pull request merged**
