### PR TITLE
Week4 ndvi

### PR DESCRIPTION
**Pull request by nanaboamah89**

### CODE REVIEW

**Comment by eefaye** [comment]
@nanaboamah89 I only made some small edits. I think it looks good and should merge so we can consider week 4 in its entirety. I also think we should put the final images in so people can check theirs looks the same.

@caitlinadams @andrewdhicks @jcrattz  any thoughts about inline code vs screenshots? Do you think we are out of the screenshot zone now? It certainly looks neater this way.

PS ignore the failed docs check, the week 3 content hasn't been pulled from master yet.

**Review by caitlinadams — CHANGES_REQUESTED** [review]
Great work, @nanaboamah89! Thank you very much for your efforts in putting this together. The example is clear and well explained.

I've restructured it a little to take the user through the process of modifying and running the notebook, as there were a few things that were different in the session 3 notebook compared to your instructions, and I wanted to make sure they matched. I will send you the notebook I've been working with so that you can work with it to develop part two of this example. 

There are a few things I noticed that may need changing:
-  The area you load has some vegetation, but mostly water. Given that the users will be calculating NDVI, it might make more sense to choose an area that's likely to have variable NDVI over the seasons. Maybe you could develop the NDVI exercise for this current area of interest and check if it shows some change. If not, it might be worth changing both to an area that has more noticeable differences in the vegetation.
- When I loaded your area of interest, I got a different number of pixels in x and y compared to you. You have (x=724, y=922), but I have (x=1448, y=1843) -- it looks like you may have loaded the data with `resolution=(-20,20)`? The session_3 notebook loads data with `resolution=(-10,10)` so I kept this the same. If you want to reduce the loading/processing time, maybe set it to `resolution=(-20,20)` and explain why you're doing that to the user.

Other than that, it's looking great! Looking forward to seeing the second part!

**Review by caitlinadams — CHANGES_REQUESTED** [review]
Hi @nanaboamah89, thanks for making the suggested changes and adding the second part! It's looking really good. I've added some additional explanation on this page and fixed some of the formatting. I have a few minor suggestions:

- The area you've selected looks good, but I think it's larger than is strictly necessary for the exercise. At the moment, it takes a long time to load the data and calculate the geomedian. The user will also have to do this twice (first for part one, then for part two), so reducing the time it takes would be valuable. Maybe try an area that's 0.01x0.01 degrees? The images won't be as good, but the user should still get value from the exercise. 
- At the moment, you've structured it so that the user makes a copy of the part one notebook to do part two. However, I was thinking it would be good for them to directly edit the part one notebook, so they end up with one notebook that does the NDVI calculation. Could you restructure the instructions to do it this way? You can look at session 3 to see an example of how we've explained it before. You should explain that we'll use the same notebook, but have to re-do the data load; this means they'll need to restart and clear all outputs, then run the notebook again step-by-step and modify the data load. Or you can instruct them to clear it, change the data load, then run all cells from the `Run` menu, then add the new cells to calculate NDVI.

**Comment by nanaboamah89** [comment]
Hi @caitlinadams , I have updated the changes, the only concern was the time for loading the data, the whole notebook take about 15 mins to run in which about 97% of the time is taken at the loading of the data.

**Comment by nanaboamah89** [comment]
I ran the notebook again, this time it took less than 2 mins to execute, using the same area.

**Pull request merged**
