### PR TITLE
Session 3 content ready for review.

### PR DESCRIPTION
**Pull request by eefaye**
Session 3 content has been drafted.

01 - cloud masking
02 - working with geomedians
03 - create a geomedian

I envision this will be merged with `master` when we are ready to push week 3 content, as there is currently no `overhaul` equivalent.
docs check fails as it is trying to find week 2 content which has not yet been merged with `master` - this should resolve itself once week 2 goes live.

### CODE REVIEW

**Review by jcrattz — CHANGES_REQUESTED** [review]
I pushed a commit that improvs some images (larger font in code cells), fixes some image names, and improves some grammar.

**Suggestion**:
In **01_cloud_masking.ipynb**, the median vs geomedian visualization in the **Comparing medians and geomedians** section does not clearly show the differences between medians and geomedians for me. I think the markers should be larger and more of the whitespace in the canvas should be used.

**Comment by eefaye** [comment]
It's getting there! @jcrattz if there is nothing else major you think needs changing, then I think it's ready for @caitlinadams to re-review.

**Review by caitlinadams — APPROVED** [review]
Amazing work @eefaye and @jcrattz! I made a few very minor changes, but otherwise I think this should be ready to go.

**Comment by oyetkin** [comment]
I think this looks good also.  As @jcrattz noted, the Median vs. Geomedian differences are subtle in the image but are explained well enough.  I would recommend a link to the paper mentioned in Slack, which was very informative for me: https://ieeexplore.ieee.org/abstract/document/8004469

One more point:  The audio for the Week 3 is very low even at maximum value.  Maybe in can be modified in an editor and re-uploaded.

**Comment by jcrattz** [comment]
@eefaye @caitlinadams I think this is ready to be pulled.

**Pull request merged**
